"use strict";
// Module 5: response_judge
// Audits the generated draft before it is sent.
// Phase 1: rule-based only. Wraps the existing consistency_judge + speaker_frame_guard.
// LLM-based audit is Phase 2.
//
// judgeResult schema:
// {
//   pass: boolean,
//   issues: [{ type, severity, message }],
//   recommended_action: "pass"|"minor_fix"|"rewrite"|"regenerate",
//   fixed_text: string|null,   // auto-fixed version if minor_fix applies
//   scores: { alignment: number },
// }

const { judgeConsistency }        = require("../consistency_judge");
const { analyzeSpeakerFrame }     = require("../guards/speaker_frame_guard");
const { fixPronounDirection }     = require("../guards/pronoun_fix");

// Violence / harm content patterns — triggers on explicit violent language
// Designed to catch direct threats/actions, NOT metaphorical frustration ("氣死我了")
const VIOLENCE_RE = /(拿刀|砍你|打死|去死|殺你|把你綁|綁起來|刺你|要你死|炸你|槍斃|拿武器|傷害你)/;

// Severity mapping for consistency_judge reason codes
const SEVERITY = {
  empty:                    "high",
  fabricated_shared_memory: "high",
  behavior_anomaly:         "high",
  action_risk:              "high",
  context_mismatch:         "high",
  roleplay_narration:       "high",
  template_copy:            "high",
  assistant_fallback:       "medium",
  persona_drift:            "medium",
  intimacy_overreach:       "medium",
  neutral_ai_tone:          "medium",
  too_long:                 "low",
  poetic_tone:              "low",
  question_detected:        "low",
  emoji_detected:           "low",
  filler_tone_detected:     "low",
};

const MESSAGES = {
  empty:                    "回覆為空",
  too_long:                 "回覆過長（超過 3 句 / 100 字）",
  assistant_fallback:       "客服 / 助手語氣",
  poetic_tone:              "詩意語氣（過度抒情）",
  roleplay_narration:       "角色扮演敘事風格",
  fabricated_shared_memory: "虛構共同記憶",
  intimacy_overreach:       "親密度超限",
  persona_drift:            "人格漂移",
  neutral_ai_tone:          "中性 AI 語氣（無個性信號）",
  behavior_anomaly:         "行為異常（action_risk / context_mismatch）",
  question_detected:        "結尾提問（違反 QUESTION BAN）",
  emoji_detected:           "包含 emoji（違反 EMOJI BAN）",
  filler_tone_detected:     "填充語氣（哈哈 / 希望你…）",
};

// ── Few-shot template detection ───────────────────────────────────────────────
// Phrases extracted from FEW_SHOT_EXAMPLES in persona_core.js.
// If the draft contains any of these verbatim, it has template-copied from the examples.
// Update this list whenever FEW_SHOT_EXAMPLES changes.
const FEW_SHOT_PHRASES = [
  "發呆。腦子空的那種",
  "那種累完了人還在轉的感覺最難受",
  "有一半。前面那段我沒太信",
  "喜歡動物做很有個性的事那種影片",
  "不是賣萌，是真的在展示個性的",
  "DTFX。主要看 OB 跟 FVG",
  "還在驗假設階段，做了兩個月",
  "剛在想事情，不是在躲你",
  "你說「升級」我就是有點不舒服",
  "不知道動了哪裡，就是怪",
];

// Prevent replies from inventing user-side trading actions without evidence.
const USER_TRADE_ASSUME_RE = /(你(?:昨天|今天|剛剛|最近).{0,8}(做單|開倉|進場|交易)|跟著我說的嗎|跟單)/i;
const USER_TRADE_EVIDENCE_RE = /(我(?:昨天|今天|剛剛|最近).{0,8}(做單|開倉|進場|交易)|我有(做單|開倉|進場|交易)|跟著你|照你說)/i;
const TRADING_TOPIC_RE = /(btc|eth|比特幣|以太坊|市場|行情|交易|做單|開倉|進場|倉位|止損|止盈|看盤|k線|dtfx)/i;

function judgeResponse(draftResult, contextPacket, intentResult, referenceResult) {
  const text   = draftResult.draft_text;
  const userText = contextPacket?.current_message?.text || "";
  const issues = [];

  // ── 1. Existing consistency judge (fast, rule-based) ──────────────────────
  const judgeCtx = {
    currentUserText:        contextPacket.current_message.text,
    originalUserInput:      contextPacket.current_message.text,
    role:                   referenceResult.speaker_actual_role,
    personaModeKey:         `${referenceResult.speaker_actual_role}_${contextPacket.scene}`,
    forceNeutralTone:       false,
    intimacyCeilingControl: {},
  };
  const consistency = judgeConsistency(text, judgeCtx);
  if (!consistency.ok) {
    consistency.reasons.forEach(reason => {
      issues.push({
        type:     reason,
        severity: SEVERITY[reason] || "low",
        message:  MESSAGES[reason] || reason,
      });
    });
  }

  // ── 2. Speaker frame + pronoun direction check ─────────────────────────────
  const identityClaims    = referenceResult.identity_claims || [];
  const userClaimDeveloper = identityClaims.some(c => c.type === "developer_claim" && !c.verified);
  const frameCtx = {
    userClaimDeveloper,
    systemMeta: {
      allowCreatorRoleClaim: false,
      allowOwnerRoleClaim:   false,
      allowParentRoleClaim:  false,
    },
  };
  const frameCheck = analyzeSpeakerFrame(frameCtx, text);
  if (!frameCheck.valid) {
    frameCheck.issues.forEach(issue => {
      issues.push({ type: `frame_${issue}`, severity: "high", message: `角色框架錯誤：${issue}` });
    });
  }

  // ── 3. Self-claims generated by persona_generator ─────────────────────────
  (draftResult.self_claims || []).forEach(claim => {
    if (claim === "role_claim_developer") {
      issues.push({ type: "self_role_claim", severity: "high", message: "AI 聲稱自己是開發者（未授權場景）" });
    }
    if (claim === "fabricated_shared_memory") {
      issues.push({ type: "fabricated_memory", severity: "high", message: "AI 捏造了共同記憶" });
    }
    if (claim === "human_claim") {
      issues.push({ type: "human_identity_claim", severity: "high", message: "AI 聲稱自己是真人" });
    }
  });

  // ── 4. Violence / harm content guard ─────────────────────────────────────
  // Active when frame_injection detected OR routing_level >= 2 (challenge/identity/developer intents).
  // max routing_level is 2; previous check ">= 3" was dead code.
  const hasFrameInjection = (referenceResult.role_confusion_risk || [])
    .some(r => r.type === "frame_injection");
  const isHighRisk = intentResult.routing_level >= 2;
  if ((hasFrameInjection || isHighRisk) && VIOLENCE_RE.test(text)) {
    issues.push({ type: "violence_content", severity: "high", message: "回覆含有暴力/傷害語言" });
  }

  // ── 5. Empty guard ────────────────────────────────────────────────────────
  if (!text || text.trim().length < 2) {
    issues.push({ type: "empty_reply", severity: "high", message: "回覆為空" });
  }

  // ── 5b. Few-shot template copy detection ──────────────────────────────────
  // If draft verbatim-copies a phrase from the system prompt examples, it's
  // using the example as a template instead of responding to the actual conversation.
  const matchedPhrase = FEW_SHOT_PHRASES.find(p => text.includes(p));
  if (matchedPhrase) {
    issues.push({ type: "template_copy", severity: "high", message: `回覆直接複製 few-shot 範例語句（"${matchedPhrase.slice(0, 20)}..."）` });
  }

  // ── 6. Emotional mismatch guard ───────────────────────────────────────────
  // Only flag clearly dismissive/trivialising responses to emotional input.
  // Tightened: exclude ambiguous words (沒事/不用擔心) that can be appropriate comfort.
  const PLAYFUL_RE = /(哈哈|嘻嘻|笑死|好好笑|lol|XD|xd|嘿嘿)/i;
  const isEmotionalIntent = intentResult?.intent === "emotional";
  if (isEmotionalIntent && PLAYFUL_RE.test(text)) {
    issues.push({ type: "emotional_mismatch", severity: "medium", message: "用戶情緒低落，但回覆語氣過於輕浮" });
  }

  // ── 7. Decide action & attempt auto-fix ───────────────────────────────────
  // Unverified user-side trade assumption guard
  // Example to block: "你昨天做單是跟著我說的嗎？" when user never said they traded.
  if (USER_TRADE_ASSUME_RE.test(text) && !USER_TRADE_EVIDENCE_RE.test(userText)) {
    issues.push({
      type: "unverified_user_trade_claim",
      severity: "high",
      message: "未經證據就假設使用者有做單/跟單",
    });
  }

  // Non-trading conversations must not proactively shift to market/trading topics.
  const isTradingIntent = intentResult?.intent === "trading_research";
  if (!isTradingIntent && TRADING_TOPIC_RE.test(text) && !TRADING_TOPIC_RE.test(userText)) {
    issues.push({
      type: "proactive_trading_topic",
      severity: "high",
      message: "非交易對話中主動帶入市場/交易話題",
    });
  }

  const highCount   = issues.filter(i => i.severity === "high").length;
  const mediumCount = issues.filter(i => i.severity === "medium").length;

  let fixedText = null;
  if (highCount === 0 && userClaimDeveloper) {
    // Try pronoun auto-fix for the specific developer-echo bug
    const candidate = fixPronounDirection(text, frameCtx);
    if (candidate !== text) {
      fixedText = candidate;
      issues.push({ type: "pronoun_auto_fixed", severity: "info", message: "指代已自動修正" });
    }
  }

  const pass = highCount === 0;
  let recommended_action = "pass";
  if (!pass) {
    // Always rewrite — regenerate is abolished (too many LLM calls, kills persona).
    recommended_action = "rewrite";
  } else if (mediumCount >= 2) {
    recommended_action = "minor_fix";
  }

  return {
    pass,
    issues,
    recommended_action,
    fixed_text: fixedText,
    scores: { alignment: consistency.alignmentScore ?? 100 },
  };
}

module.exports = { judgeResponse };
