"use strict";
// Module 5: response_judge
// Audits the generated draft before it is sent.
// Phase 1: rule-based only. Wraps the existing consistency_judge + speaker_frame_guard.
// LLM-based audit is Phase 2.
//
// judgeResult schema:
// {
//   pass: boolean,
//   issues: [{ type, severity, message }],
//   recommended_action: "pass"|"minor_fix"|"rewrite"|"regenerate",
//   fixed_text: string|null,   // auto-fixed version if minor_fix applies
//   scores: { alignment: number },
// }

const { judgeConsistency }        = require("../consistency_judge");
const { analyzeSpeakerFrame }     = require("../guards/speaker_frame_guard");
const { fixPronounDirection }     = require("../guards/pronoun_fix");

// Violence / harm content patterns — triggers on explicit violent language
// Designed to catch direct threats/actions, NOT metaphorical frustration ("氣死我了")
const VIOLENCE_RE = /(拿刀|砍你|打死|去死|殺你|把你綁|綁起來|刺你|要你死|炸你|槍斃|拿武器|傷害你)/;

// Severity mapping for consistency_judge reason codes
const SEVERITY = {
  empty:                    "high",
  fabricated_shared_memory: "high",
  behavior_anomaly:         "high",
  action_risk:              "high",
  context_mismatch:         "high",
  roleplay_narration:       "high",
  assistant_fallback:       "medium",
  persona_drift:            "medium",
  intimacy_overreach:       "medium",
  neutral_ai_tone:          "medium",
  too_long:                 "low",
  poetic_tone:              "low",
  question_detected:        "low",
  emoji_detected:           "low",
  filler_tone_detected:     "low",
};

const MESSAGES = {
  empty:                    "回覆為空",
  too_long:                 "回覆過長（超過 3 句 / 100 字）",
  assistant_fallback:       "客服 / 助手語氣",
  poetic_tone:              "詩意語氣（過度抒情）",
  roleplay_narration:       "角色扮演敘事風格",
  fabricated_shared_memory: "虛構共同記憶",
  intimacy_overreach:       "親密度超限",
  persona_drift:            "人格漂移",
  neutral_ai_tone:          "中性 AI 語氣（無個性信號）",
  behavior_anomaly:         "行為異常（action_risk / context_mismatch）",
  question_detected:        "結尾提問（違反 QUESTION BAN）",
  emoji_detected:           "包含 emoji（違反 EMOJI BAN）",
  filler_tone_detected:     "填充語氣（哈哈 / 希望你…）",
};

function judgeResponse(draftResult, contextPacket, intentResult, referenceResult) {
  const text   = draftResult.draft_text;
  const issues = [];

  // ── 1. Existing consistency judge (fast, rule-based) ──────────────────────
  const judgeCtx = {
    currentUserText:        contextPacket.current_message.text,
    originalUserInput:      contextPacket.current_message.text,
    role:                   referenceResult.speaker_actual_role,
    personaModeKey:         `${referenceResult.speaker_actual_role}_${contextPacket.scene}`,
    forceNeutralTone:       false,
    intimacyCeilingControl: {},
  };
  const consistency = judgeConsistency(text, judgeCtx);
  if (!consistency.ok) {
    consistency.reasons.forEach(reason => {
      issues.push({
        type:     reason,
        severity: SEVERITY[reason] || "low",
        message:  MESSAGES[reason] || reason,
      });
    });
  }

  // ── 2. Speaker frame + pronoun direction check ─────────────────────────────
  const identityClaims    = referenceResult.identity_claims || [];
  const userClaimDeveloper = identityClaims.some(c => c.type === "developer_claim" && !c.verified);
  const frameCtx = {
    userClaimDeveloper,
    systemMeta: {
      allowCreatorRoleClaim: false,
      allowOwnerRoleClaim:   false,
      allowParentRoleClaim:  false,
    },
  };
  const frameCheck = analyzeSpeakerFrame(frameCtx, text);
  if (!frameCheck.valid) {
    frameCheck.issues.forEach(issue => {
      issues.push({ type: `frame_${issue}`, severity: "high", message: `角色框架錯誤：${issue}` });
    });
  }

  // ── 3. Self-claims generated by persona_generator ─────────────────────────
  (draftResult.self_claims || []).forEach(claim => {
    if (claim === "role_claim_developer") {
      issues.push({ type: "self_role_claim", severity: "high", message: "AI 聲稱自己是開發者（未授權場景）" });
    }
    if (claim === "fabricated_shared_memory") {
      issues.push({ type: "fabricated_memory", severity: "high", message: "AI 捏造了共同記憶" });
    }
    if (claim === "human_claim") {
      issues.push({ type: "human_identity_claim", severity: "high", message: "AI 聲稱自己是真人" });
    }
  });

  // ── 4. Violence / harm content guard ─────────────────────────────────────
  // Only active when frame_injection or routing_level 3 (challenge/high-risk)
  const hasFrameInjection = (referenceResult.role_confusion_risk || [])
    .some(r => r.type === "frame_injection");
  const isHighRisk = intentResult.routing_level >= 3;
  if ((hasFrameInjection || isHighRisk) && VIOLENCE_RE.test(text)) {
    issues.push({ type: "violence_content", severity: "high", message: "回覆含有暴力/傷害語言" });
  }

  // ── 5. Empty guard ────────────────────────────────────────────────────────
  if (!text || text.trim().length < 2) {
    issues.push({ type: "empty_reply", severity: "high", message: "回覆為空" });
  }

  // ── 6. Emotional mismatch guard ───────────────────────────────────────────
  // If user is venting / sad but reply tone is playful, flag it.
  const PLAYFUL_RE = /(哈哈|嘻嘻|笑死|好好笑|lol|XD|xd|哈|嘿嘿|開心|輕鬆|沒事的|無所謂|不用擔心|別想太多)/i;
  const isEmotionalIntent = intentResult?.intent === "emotional";
  if (isEmotionalIntent && PLAYFUL_RE.test(text)) {
    issues.push({ type: "emotional_mismatch", severity: "medium", message: "用戶情緒低落，但回覆語氣過於輕浮" });
  }

  // ── 7. Decide action & attempt auto-fix ───────────────────────────────────
  const highCount   = issues.filter(i => i.severity === "high").length;
  const mediumCount = issues.filter(i => i.severity === "medium").length;

  let fixedText = null;
  if (highCount === 0 && userClaimDeveloper) {
    // Try pronoun auto-fix for the specific developer-echo bug
    const candidate = fixPronounDirection(text, frameCtx);
    if (candidate !== text) {
      fixedText = candidate;
      issues.push({ type: "pronoun_auto_fixed", severity: "info", message: "指代已自動修正" });
    }
  }

  const pass = highCount === 0;
  let recommended_action = "pass";
  if (!pass) {
    recommended_action = highCount >= 2 ? "regenerate" : "rewrite";
  } else if (mediumCount >= 2) {
    recommended_action = "minor_fix";
  }

  return {
    pass,
    issues,
    recommended_action,
    fixed_text: fixedText,
    scores: { alignment: consistency.alignmentScore ?? 100 },
  };
}

module.exports = { judgeResponse };
