const { PERSONALITY_BASELINE } = require("./personality_baseline");

function buildReasonCodes(reasonCodes) {
  return Array.from(new Set(reasonCodes.filter(Boolean)));
}

function getTopTag(profile = {}) {
  const tags = Object.entries(profile.tags || {}).sort((a, b) => b[1] - a[1]);
  return tags[0]?.[0] || null;
}

// Template messages are forbidden — initiative context is passed to LLM for organic generation.
// Do NOT generate hardcoded follow-up sentences here.

function getInitiativeDecision(input = {}) {
  const {
    identity = {},
    relationshipProfile = {},
    relationship = {},
    conversationMemory = {},
    identityMemory = {},
    inertiaState = {},
    silenceStats = {},
  } = input;
  const role = identity.role || "public_user";
  const channel = identity.channel || "public";
  const familiarity = relationshipProfile.familiarity || relationship.familiarity || 0;
  const reasonCodes = [];

  if (channel === "group" && familiarity < PERSONALITY_BASELINE.initiativeMinFamiliarity) {
    return { shouldInitiate: false, targetUserId: null, initiativeContext: null, reasonCodes: ["low_familiarity"] };
  }

  if (inertiaState.currentIntent === "scrolling") {
    return { shouldInitiate: false, targetUserId: null, initiativeContext: null, reasonCodes: ["scrolling_mode"] };
  }

  const lastInteractionAt = relationship.lastInteractionAt || 0;
  if (channel === "group" && lastInteractionAt && Date.now() - lastInteractionAt > 24 * 60 * 60 * 1000) {
    return { shouldInitiate: false, targetUserId: null, initiativeContext: null, reasonCodes: ["stale_group_target"] };
  }

  // Determine whether there's genuine context to speak — no template drafts.
  // Actual message content is always generated by the LLM (proactive_scheduler).
  const hasLastTopic = Boolean(relationship.lastTopic);
  const topTag = getTopTag(identityMemory.preferenceProfile || {});
  const hasPreference = Boolean(topTag);
  const hasInitiationHint = Boolean(channel === "private" && relationshipProfile.initiationText);

  if (!hasLastTopic && !hasPreference && !hasInitiationHint) {
    return { shouldInitiate: false, targetUserId: null, initiativeContext: null, reasonCodes: ["no_contextual_reason"] };
  }

  if (hasLastTopic) reasonCodes.push("last_topic");
  if (hasPreference) reasonCodes.push("preference_tag");
  if (hasInitiationHint) reasonCodes.push("relationship_initiation");
  if (role === "developer") reasonCodes.push("developer_bias");
  if (silenceStats.isChatSilent) reasonCodes.push("chat_silence");

  return {
    shouldInitiate: true,
    targetUserId: identity.userId || null,
    // Context signals for the LLM — NOT a pre-written message
    initiativeContext: {
      lastTopic: relationship.lastTopic || null,
      topPreferenceTag: topTag || null,
    },
    reasonCodes: buildReasonCodes(reasonCodes),
  };
}

module.exports = {
  getInitiativeDecision,
};
